# Generated by Django 4.0.3 on 2022-04-24 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='locality_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
