# Generated by Django 4.0.4 on 2022-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_phone_alter_customer_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='txn_id',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RAM', 'RAM'), ('SSD', 'Solid State Drive'), ('HDD', 'Hard Disk Drive'), ('MB', 'Mother Board'), ('PSU', 'Power Supply Unit'), ('CB', 'Cabinet'), ('UPS', 'UPS'), ('PND', 'Pendrive'), ('MOU', 'Mouse'), ('KB', 'Keyboard')], max_length=3),
        ),
    ]
