# Generated by Django 4.0.4 on 2022-05-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
