# Generated by Django 4.0.4 on 2022-05-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderplaced_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
