# Generated by Django 4.0.6 on 2024-08-12 07:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(validators=[app.models.validate_phone_length]),
        ),
    ]
